// Offline Ring 2 data-prep script (Phase 15B). Run once, by hand, against
// a local Overpass extract — never invoked by the shipped app. Emits a
// static TypeScript data file that the app imports directly, so nothing
// in Oyi-Twin-Engine ever queries OSM/Overpass at runtime.
import fs from "node:fs";

// Phase 15C — nudged ~99m north from the original Phase 15B anchor so
// Luna reads as a credible Ahmadu Bello Way frontage/setback site. Must
// stay in sync with LUNA_SITE_ANCHOR in src/luna/lunaSite.ts.
const ANCHOR = { lat: 6.4222, lon: 3.4238 };
const HEADING_DEG = 0;
const RING1_ENVELOPE = { minX: -39, maxX: 39, minZ: -36, maxZ: 50 };
const KEEP_RADIUS = 650; // a little past Ring 2's 500m so edges don't look clipped

function metersPerDegLat(latDeg) {
  const phi = (latDeg * Math.PI) / 180;
  return 111132.92 - 559.82 * Math.cos(2 * phi) + 1.175 * Math.cos(4 * phi) - 0.0023 * Math.cos(6 * phi);
}
function metersPerDegLon(latDeg) {
  const phi = (latDeg * Math.PI) / 180;
  return 111412.84 * Math.cos(phi) - 93.5 * Math.cos(3 * phi) + 0.118 * Math.cos(5 * phi);
}
function geoToLocal(lat, lon) {
  const east = (lon - ANCHOR.lon) * metersPerDegLon(ANCHOR.lat);
  const north = (lat - ANCHOR.lat) * metersPerDegLat(ANCHOR.lat);
  const theta = (HEADING_DEG * Math.PI) / 180;
  const x = east * Math.cos(theta) - north * Math.sin(theta);
  const z = east * Math.sin(theta) + north * Math.cos(theta);
  return [x, z];
}

function hash(n) {
  // Small deterministic integer hash — same "controlled variation, never
  // Math.random()" convention already established by LevelFacade's
  // windowState(). Not cryptographic, just needs to be stable/repeatable.
  let h = Math.imul(n ^ 0x9e3779b9, 2654435761) >>> 0;
  h ^= h >>> 15;
  return h;
}

const ROAD_WIDTH_BY_CLASS = {
  trunk: 12,
  primary: 10,
  secondary: 8,
  tertiary: 7,
  tertiary_link: 6,
  secondary_link: 6,
  residential: 6,
  unclassified: 5.5,
  service: 4,
  footway: 2,
};

function loadElements(path) {
  return JSON.parse(fs.readFileSync(path, "utf8")).elements;
}

const mainExtract = loadElements(new URL("./osm-raw/vi_extract.json", import.meta.url));

// --- Roads ---
const roadSegments = [];
let roadCount = 0;
for (const el of mainExtract) {
  const tags = el.tags || {};
  if (!tags.highway || !el.geometry) continue;
  const width = ROAD_WIDTH_BY_CLASS[tags.highway] ?? 4.5;
  const pts = el.geometry.map((g) => geoToLocal(g.lat, g.lon));
  let kept = false;
  for (let i = 0; i < pts.length - 1; i++) {
    const [x1, z1] = pts[i];
    const [x2, z2] = pts[i + 1];
    const midX = (x1 + x2) / 2;
    const midZ = (z1 + z2) / 2;
    const dist = Math.hypot(midX, midZ);
    if (dist > KEEP_RADIUS) continue;
    const length = Math.hypot(x2 - x1, z2 - z1);
    if (length < 0.5) continue;
    const rotationY = Math.atan2(x2 - x1, z2 - z1); // bearing-style angle in local XZ
    roadSegments.push({ x: round2(midX), z: round2(midZ), length: round2(length), rotationY: round4(rotationY), width, cls: tags.highway });
    kept = true;
  }
  if (kept) roadCount++;
}

// --- Buildings ---
const buildings = [];
let culledInRing1 = 0;
for (const el of mainExtract) {
  const tags = el.tags || {};
  if (!tags.building || !el.geometry || el.geometry.length < 3) continue;
  const pts = el.geometry.map((g) => geoToLocal(g.lat, g.lon));
  const xs = pts.map((p) => p[0]);
  const zs = pts.map((p) => p[1]);
  const minX = Math.min(...xs), maxX = Math.max(...xs);
  const minZ = Math.min(...zs), maxZ = Math.max(...zs);
  const centerX = (minX + maxX) / 2;
  const centerZ = (minZ + maxZ) / 2;
  const width = Math.max(maxX - minX, 2);
  const depth = Math.max(maxZ - minZ, 2);
  const dist = Math.hypot(centerX, centerZ);
  if (dist > KEEP_RADIUS) continue;

  // Cull anything intersecting the conceptual Luna Ring 1 envelope — the
  // real parcel underneath/adjacent to the anchor must never render as if
  // it were the proposed Luna site (Phase 15B §3).
  const overlapsRing1 =
    minX < RING1_ENVELOPE.maxX && maxX > RING1_ENVELOPE.minX && minZ < RING1_ENVELOPE.maxZ && maxZ > RING1_ENVELOPE.minZ;
  if (overlapsRing1) {
    culledInRing1++;
    continue;
  }

  const seed = Math.round(centerX * 100) ^ Math.round(centerZ * 100) ^ el.id;
  const h = hash(seed);
  // Low/mid-rise commercial+residential mix, consistent with this part of
  // VI — deterministic pseudo-height, real per-building height data isn't
  // available at this fidelity (Phase 15A §6/§11).
  const height = 8 + (h >>> 0) % 14 * 2.5;

  buildings.push({ x: round2(centerX), z: round2(centerZ), width: round2(width), depth: round2(depth), height: round1(height) });
}

function round1(n) { return Math.round(n * 10) / 10; }
function round2(n) { return Math.round(n * 100) / 100; }
function round4(n) { return Math.round(n * 10000) / 10000; }

const out = `// AUTO-GENERATED by scripts/offline OSM prep (Phase 15B) — do not hand-edit.
// Source: OpenStreetMap via Overpass API. See OSM_ATTRIBUTION.md for full
// provenance (extraction date, bounding box, ODbL attribution).
//
// Coordinates are already projected into Luna's local metre-based scene
// frame via src/engine/geo/projection.ts's geoToLocal, anchored at
// LUNA_SITE_ANCHOR (src/luna/lunaSite.ts). Buildings overlapping the
// conceptual Luna Ring 1 envelope have been removed — see lunaSite.ts's
// LUNA_RING1_ENVELOPE doc.

export interface Ring2RoadSegment {
  x: number;
  z: number;
  length: number;
  rotationY: number;
  width: number;
  cls: string;
}

export interface Ring2Building {
  x: number;
  z: number;
  width: number;
  depth: number;
  height: number;
}

export const RING2_ROAD_SEGMENTS: Ring2RoadSegment[] = ${JSON.stringify(roadSegments)};

export const RING2_BUILDINGS: Ring2Building[] = ${JSON.stringify(buildings)};
`;

fs.writeFileSync(new URL("../src/luna/site/lunaRing2Data.ts", import.meta.url), out);
console.log(`roads: ${roadCount} ways -> ${roadSegments.length} segments`);
console.log(`buildings kept: ${buildings.length}, culled (Ring1 overlap): ${culledInRing1}`);
