import {createServer} from 'vite';import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';
const dir='artifacts/l01-interior-v1';const server=await createServer({server:{middlewareMode:true},appType:'custom'});
try{
 const load=p=>server.ssrLoadModule('/src/'+p),checks=[];const test=(name,f)=>{f();checks.push(name)};
 const {L01_FURNISHINGS:items,L01_OBSTACLES:bounds,L01_POOL_STUDY:pool}=await load('luna/architecture/l01InteriorLayout.ts');
 const {PODIUM_PASSAGES:paths}=await load('luna/architecture/podiumPassages.ts');const {podiumStepAllowed:allowed}=await load('luna/explore/podiumWalkability.ts');
 const {LUNA_CORES:cores,LUNA_LEVELS:levels}=await load('luna/lunaProgramme.ts');const {LUNA_L01_CLUB:club}=await load('luna/interiors/lunaInteriors.ts');
 const {buildL01Interior}=await load('luna/architecture/l01InteriorGeometry.ts');const {buildGroundInterior}=await load('luna/architecture/groundInterior/groundInteriorGeometry.ts');
 test('All established L01 routes retain 0.9m clear furnishing envelope',()=>{for(const t of paths.filter(t=>t.fromSpaceRef.startsWith('LUNA-L01'))){const p=t.crossingPath;for(let i=1;i<p.length;i++){const a=p[i-1],b=p[i],n=Math.max(1,Math.ceil(Math.hypot(b.x-a.x,b.z-a.z)/.025));for(let j=0;j<=n;j++){const x=a.x+(b.x-a.x)*j/n,z=a.z+(b.z-a.z)*j/n;assert(!bounds.some(r=>Math.abs(x-r.x)<r.width/2+.45&&Math.abs(z-r.z)<r.depth/2+.45),t.transitionId);}}}});
 test('Canonical doors, lift approaches and manual common corridor stay open',()=>{for(const r of club.rooms){assert(allowed({x:0,y:6.7,z:5.2},{x:r.x,y:6.7,z:5.2},true));assert(allowed({x:r.x,y:6.7,z:5.2},{x:r.x,y:6.7,z:2.8},true));}for(const x of [-3,0,3,6.5])assert(allowed({x,y:6.7,z:5.2},{x,y:6.7,z:2.96},true));});
 test('Pool is non-structural, non-operational and cannot be walked across',()=>{assert.equal(pool.structuralBasin,false);assert.equal(pool.operationalAsset,false);assert(pool.surfaceY>=0&&pool.surfaceY<.1);assert(!allowed({x:pool.x,y:6.7,z:1},{x:pool.x,y:6.7,z:-3},true));assert(allowed({x:-12.85,y:6.7,z:1},{x:-12.85,y:6.7,z:-10.5},true));});
 test('Decoration avoids every protected core/stair/riser footprint',()=>{for(const b of bounds)for(const c of cores)assert(!(Math.abs(b.x-c.x)<(b.width+c.width)/2+.1&&Math.abs(b.z-c.z)<(b.depth+c.depth)/2+.1),JSON.stringify({b,c}));});
 test('Ground geometry and instance transforms remain byte-identical after helper reuse',()=>{const expected=JSON.parse(readFileSync(dir+'/ground-geometry-before.json'));const actual=buildGroundInterior().map(b=>{const h=createHash('sha256');for(const a of Object.values(b.geometry.attributes))h.update(Buffer.from(a.array.buffer));h.update(Buffer.from(b.geometry.index.array.buffer));return{key:b.key,hash:h.digest('hex'),...(b.instances?{instances:b.instances}:{})}});assert.deepEqual(actual,expected)});
 const baseline=JSON.parse(readFileSync(dir+'/inherited-source.json'));
 const allowedChanges=['src/luna/InteriorLayer.tsx','src/luna/architecture/PodiumCoreApproach.tsx','src/luna/lift/DynamicLift.tsx','src/luna/explore/podiumWalkability.ts','src/luna/architecture/groundInterior/groundInteriorGeometry.ts','src/luna/architecture/groundInterior/GroundInteriorFinishes.tsx','src/luna/architecture/groundInterior/GroundInteriorLettering.tsx'];
 test('All other inherited source, policy, canonical geometry and existing test scripts remain byte-identical',()=>{for(const[p,h]of Object.entries(baseline)){if(allowedChanges.includes(p))continue;assert.equal(createHash('sha256').update(readFileSync(p)).digest('hex'),h,p)}});
 test('L01 coordinates, room programme and clear-height authority unchanged',()=>{const l=levels.find(l=>l.ref===club.ownerLevelRef);assert.equal(l.baseElevation,5);assert.equal(l.height,3.5);assert.deepEqual(l.footprint,{width:40,depth:30});assert.equal(club.rooms.length,2);for(const r of club.rooms){assert.equal(r.width,9);assert.equal(r.depth,16);assert.equal(r.z,-4)}});
 const batches=buildL01Interior();let bytes=0,uploaded=0,expanded=0;for(const b of batches){const n=b.geometry.index.count/3;uploaded+=n;expanded+=n*(b.instances?.length??1);bytes+=b.geometry.index.array.byteLength+Object.values(b.geometry.attributes).reduce((s,a)=>s+a.array.byteLength,0)}
 test('Shared indexed construction remains below 50k expanded decorative triangles and 3MB buffers',()=>{assert(expanded<50000);assert(bytes<3000000);assert(batches.length<=13);assert.equal(batches.find(b=>b.key==='foliage').instances.length,3)});
 test('No furnishings exceed coordinated room ceiling',()=>{for(const b of batches){b.geometry.computeBoundingBox();assert(b.geometry.boundingBox.max.y<=2.85,b.key)}});
 writeFileSync(dir+'/deterministic.json',JSON.stringify({passed:true,checks,items,bounds,pool,uploadedTriangles:uploaded,expandedTriangles:expanded,bufferBytes:bytes,materialBatches:batches.length,allowedChangedFiles:allowedChanges},null,2));console.log(checks.join('\n'));batches.forEach(b=>b.geometry.dispose());
}finally{await server.close()}
